### ISSUE TITLE
theme = zplit, best Zola port

### ISSUE THREAD

**Issue by FutureLearnSole** [gicrisf/zplit#1]
https://github.com/gicrisf/zplit/blame/42f6232b2e383728950f43661a7dedaaecb02ab0/README.md#L17

`theme = zplit` `theme = zplit` `theme = zplit` 

_Assalamualaikum_

**Comment by gicrisf** [comment]
I'm sorry, but I don't understand: how can I help you?

**Comment by JomeierFL** [comment]
I think the installation instructions should say to set

`theme = "zplit"`

instead of

`theme = "zhuia"`

**Comment by YufeiZhan** [comment]
Encountered the same issue, solved exactly as the above.

**Comment by gicrisf** [comment]
I'm really sorry I disappeared lately: I was going through a lot and I had to take a break. Now, I can finally see what the issue was about, and I'm grateful to all of you for bringing it to my attention. During that time, I was working on two themes and I think I may have accidentally written one theme name for another. The README should be fine, now.
